 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Jairo
 */
public class Cierres extends javax.swing.JFrame {

    /**
     * Creates new form Cierres
     */
    public Cierres() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labeltotal = new javax.swing.JLabel();
        labelunidades = new javax.swing.JLabel();
        labelfecha4 = new javax.swing.JLabel();
        labeltickets = new javax.swing.JLabel();
        labeldevoluciones = new javax.swing.JLabel();
        labelfecha7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelfecha5 = new javax.swing.JLabel();
        importedevs = new javax.swing.JLabel();
        labelfecha6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CIERRE DEL DIA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 20, -1, -1));

        labelfecha.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        labelfecha.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha.setText("fecha");
        getContentPane().add(labelfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Unidades:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total facturado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 103, -1, -1));

        labeltotal.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labeltotal.setForeground(new java.awt.Color(255, 255, 255));
        labeltotal.setText("total");
        getContentPane().add(labeltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 103, -1, -1));

        labelunidades.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labelunidades.setForeground(new java.awt.Color(255, 255, 255));
        labelunidades.setText("fecha");
        getContentPane().add(labelunidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 134, -1, -1));

        labelfecha4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labelfecha4.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha4.setText("Devoluciones:");
        getContentPane().add(labelfecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 196, -1, -1));

        labeltickets.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labeltickets.setForeground(new java.awt.Color(255, 255, 255));
        labeltickets.setText("fecha");
        getContentPane().add(labeltickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 165, -1, -1));

        labeldevoluciones.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labeldevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        labeldevoluciones.setText("dev");
        getContentPane().add(labeldevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 196, -1, -1));

        labelfecha7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labelfecha7.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha7.setText("Tickets:");
        getContentPane().add(labelfecha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 165, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaccion.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 110, 80));

        labelfecha5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        labelfecha5.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha5.setText("Efectuar cierre");
        getContentPane().add(labelfecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        importedevs.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        importedevs.setForeground(new java.awt.Color(255, 255, 255));
        importedevs.setText("dev");
        getContentPane().add(importedevs, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 229, -1, -1));

        labelfecha6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labelfecha6.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha6.setText("Importe Devoluciones:");
        getContentPane().add(labelfecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 229, -1, -1));

        fondo.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        fondo.setText("fondo");
        fondo.setPreferredSize(new java.awt.Dimension(501, 410));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static CierreLotes cierrelotes = new CierreLotes();
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Principal.bd.CierreDataBase(labelfecha.getText(), labeltotal.getText(), labelunidades.getText(), labeltickets.getText(),labeldevoluciones.getText(), importedevs.getText());
        cierrelotes.IniciarBarra();
        cierrelotes.setVisible(true);    
        this.setVisible(false);
        labelfecha.setText("");
        labeltotal.setText("");
        labelunidades.setText("");
        labeltickets.setText("");
        labeldevoluciones.setText("");
        importedevs.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cierres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cierres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cierres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cierres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cierres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    public javax.swing.JLabel importedevs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel labeldevoluciones;
    public static javax.swing.JLabel labelfecha;
    private javax.swing.JLabel labelfecha4;
    private javax.swing.JLabel labelfecha5;
    private javax.swing.JLabel labelfecha6;
    private javax.swing.JLabel labelfecha7;
    public javax.swing.JLabel labeltickets;
    public javax.swing.JLabel labeltotal;
    public javax.swing.JLabel labelunidades;
    // End of variables declaration//GEN-END:variables
}
