/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jairo
 */
public class Comisiones extends javax.swing.JFrame {
    
    public static DefaultTableModel modelocomisiones = new DefaultTableModel() { // HAGO QUE LAS CELDAS NO SEAN EDITABLES 
        @Override
        public boolean isCellEditable(int row, int column) {
            if (column == 4) {
                return true;

            } else {
                return false;

            }

        }

    };
 
    
    
    
    
    
    public Comisiones() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        tablacomisiones.setModel(modelocomisiones);
        modelocomisiones.addColumn("Fecha");
        modelocomisiones.addColumn("Vendedor");
        modelocomisiones.addColumn("Unidades");
        modelocomisiones.addColumn("Monto");
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        combovendedor = new javax.swing.JComboBox<>();
        calendardesde = new com.toedter.calendar.JDateChooser();
        calendarhasta = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacomisiones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totallocal = new javax.swing.JLabel();
        ulocal = new javax.swing.JLabel();
        tlocal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel1.setText("Desde:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combovendedor.setBackground(new java.awt.Color(153, 153, 153));
        combovendedor.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        combovendedor.setForeground(new java.awt.Color(0, 0, 0));
        combovendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "889", "240" }));
        getContentPane().add(combovendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));

        calendardesde.setBackground(new java.awt.Color(153, 153, 153));
        calendardesde.setForeground(new java.awt.Color(0, 0, 0));
        calendardesde.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(calendardesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 130, 30));

        calendarhasta.setBackground(new java.awt.Color(153, 153, 153));
        calendarhasta.setForeground(new java.awt.Color(0, 0, 0));
        calendarhasta.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(calendarhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 130, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vendedor: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desde:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        tablacomisiones.setBackground(new java.awt.Color(204, 204, 204));
        tablacomisiones.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        tablacomisiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablacomisiones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 560, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unidades:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tickets:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        totallocal.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        totallocal.setForeground(new java.awt.Color(255, 255, 255));
        totallocal.setText("0");
        getContentPane().add(totallocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        ulocal.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        ulocal.setForeground(new java.awt.Color(255, 255, 255));
        ulocal.setText("0");
        getContentPane().add(ulocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, -1));

        tlocal.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        tlocal.setForeground(new java.awt.Color(255, 255, 255));
        tlocal.setText("0");
        getContentPane().add(tlocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 80, 39));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hasta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        fondo.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        fondo.setText("Total:");
        fondo.setPreferredSize(new java.awt.Dimension(756, 645));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                try {
            ListaComisiones.bandera = false;
            Date date = calendardesde.getDate();
            String obtenerfecha = new SimpleDateFormat("dd-MM-yyyy").format(date);
            Date date2 = calendarhasta.getDate();
            String obtenerfecha2 = new SimpleDateFormat("dd-MM-yyyy").format(date2);
            
            String obtenervendedor = String.valueOf (combovendedor.getSelectedItem());

            String dia_ini = obtenerfecha.substring(0, 2);
            String mes_ini = obtenerfecha.substring(3, 5);
            String year_ini = obtenerfecha.substring(6, 10);

            String dia_fin = obtenerfecha2.substring(0, 2);
            String mes_fin = obtenerfecha2.substring(3, 5);
            String year_fin = obtenerfecha2.substring(6, 10);

            int idia = Principal.listacomisiones.ParsearCadena(dia_ini);
            int imes = Principal.listacomisiones.ParsearCadena(mes_ini);
            int iyear = Principal.listacomisiones.ParsearCadena(year_ini);

            int fdia = Principal.listacomisiones.ParsearCadena(dia_fin);
            int fmes = Principal.listacomisiones.ParsearCadena(mes_fin);
            int fyear = Principal.listacomisiones.ParsearCadena(year_fin);

            if (iyear > fyear) {                                                                                                                                           //VALIDACIONES PARA QUE EL USUARIO NO INTRODUZCA MAL LAS FECHAS.
                JOptionPane.showMessageDialog(null, "La fecha final no puede ser menor que la inicial.");

            } else if (iyear == fyear) {

                if (imes > fmes) {
                    JOptionPane.showMessageDialog(null, "La fecha final no puede ser menor que la inicial.");
                } else if (imes == fmes) {

                    if (idia > fdia) {
                        JOptionPane.showMessageDialog(null, "La fecha final no puede ser menor que la inicial.");

                    }else{
                    Principal.listacomisiones.AsignoValores(obtenerfecha, obtenerfecha2, obtenervendedor);
                    
                    }

                } else {
                    Principal.listacomisiones.AsignoValores(obtenerfecha, obtenerfecha2,obtenervendedor);

                }

            } else {

                Principal.listacomisiones.AsignoValores(obtenerfecha, obtenerfecha2,obtenervendedor);
            }
            
            Principal.listacomisiones.TotalesLocal();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Por favor ingrese las fechas correctamente.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        combovendedor.setSelectedIndex(0);
        calendardesde.setDate(Principal.fecha);
        calendarhasta.setDate(Principal.fecha);
        totallocal.setText("");
        ulocal.setText("");
        tlocal.setText("");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comisiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendardesde;
    private com.toedter.calendar.JDateChooser calendarhasta;
    private java.awt.Choice choice1;
    private javax.swing.JComboBox<String> combovendedor;
    public static javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablacomisiones;
    public static javax.swing.JLabel tlocal;
    public static javax.swing.JLabel totallocal;
    public static javax.swing.JLabel ulocal;
    // End of variables declaration//GEN-END:variables
}
