/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Base_datos.BaseDatos;
import Logica.*;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Jairo
 */
public class Facturacion extends javax.swing.JFrame {

    public static DefaultTableModel modelofacturacion = new DefaultTableModel() { // HAGO QUE LAS CELDAS NO SEAN EDITABLES 
        @Override
        public boolean isCellEditable(int row, int column) {
            if (column == 4) {
                return true;

            } else {
                return false;

            }

        }

    };

    public static int numfactura;
    public static double montototal;
    public static double auxiliarmonto; // ME AYUDA A GUARDAR TEMPORALMENTE MONTOTOTAL PARA USARLO EN EL BOTON DE PAGAR. 
    public static int banderacambio = 0;
    public static int itemstotal;
    public static int aiuda = 0; // CHEQUEAR PARA QUE MIERDA SIRVE ESTO.
    public static CerrarFactura cerrarfactura = new CerrarFactura();
    public static MediodePago mediodepago = new MediodePago();
    public static InterfazCambio interfazcambio = new InterfazCambio();
    public static int banderadevolucion = 0; // BANDERA QUE SE ENCIENDE SI ESTA EN MODO DEVOLUCION. 
    public static JTableHeader header; // HEADER DE LA TABLA PARA CAMBIAR EL COLOR.

    public static int auxstock = 0; // BANDERA USADA AL PRESIONAR EL BOTON "PAGAR" PARA CHEQUEAR SI HAY EXISTENCIA DEL STOCK REQUERIDO.

    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        tablafacturacion.setModel(modelofacturacion);
        modelofacturacion.addColumn("Codigo");
        modelofacturacion.addColumn("Descripcion");
        modelofacturacion.addColumn("Precio");
        modelofacturacion.addColumn("Cantidad");
        txtprecio.setEditable(false);
        txtdescripcion.setEditable(false);
        txtcantidad.setEditable(true);
        header = tablafacturacion.getTableHeader(); // INSTANCIO EL HEADER EN EL CONSTRUCTOR DE LA INTERFAZ. 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoncajero = new javax.swing.JButton();
        botonvendedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafacturacion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        labelmonto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelitems = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botoncliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        botonstock = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        fechalabel = new javax.swing.JLabel();
        labelfactura = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(925, 696));
        setPreferredSize(new java.awt.Dimension(913, 660));
        setSize(new java.awt.Dimension(792, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botoncajero.setBackground(new java.awt.Color(153, 153, 153));
        botoncajero.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        botoncajero.setForeground(new java.awt.Color(0, 0, 0));
        botoncajero.setText("Cajero");
        botoncajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncajeroActionPerformed(evt);
            }
        });
        getContentPane().add(botoncajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 130, 30));

        botonvendedor.setBackground(new java.awt.Color(153, 153, 153));
        botonvendedor.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        botonvendedor.setForeground(new java.awt.Color(0, 0, 0));
        botonvendedor.setText("Vendedor");
        botonvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvendedorActionPerformed(evt);
            }
        });
        getContentPane().add(botonvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 150, 30));

        tablafacturacion.setBackground(new java.awt.Color(204, 204, 204));
        tablafacturacion.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        tablafacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablafacturacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 360, 540));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IMPORTE: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, -1, -1));

        labelmonto.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        labelmonto.setForeground(new java.awt.Color(255, 255, 255));
        labelmonto.setText("€");
        getContentPane().add(labelmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 100, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ITEMS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        labelitems.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        labelitems.setForeground(new java.awt.Color(255, 255, 255));
        labelitems.setText("0");
        getContentPane().add(labelitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 100, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Factura: #");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 90, -1));

        labelfecha.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        labelfecha.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha.setText("Fecha:");
        getContentPane().add(labelfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingreso de producto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        botoncliente.setBackground(new java.awt.Color(153, 153, 153));
        botoncliente.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        botoncliente.setForeground(new java.awt.Color(0, 0, 0));
        botoncliente.setText("Cliente: Consumidor Final");
        botoncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonclienteActionPerformed(evt);
            }
        });
        getContentPane().add(botoncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 200, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pagar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 50, -1));

        txtcodigo.setBackground(new java.awt.Color(153, 153, 153));
        txtcodigo.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcodigoFocusLost(evt);
            }
        });
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 190, 30));

        botonstock.setBackground(new java.awt.Color(153, 153, 153));
        botonstock.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        botonstock.setForeground(new java.awt.Color(0, 0, 0));
        botonstock.setText("...");
        botonstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonstockActionPerformed(evt);
            }
        });
        getContentPane().add(botonstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 40, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Modo Cambio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 140, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 70, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 50, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cancelar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 70, -1));

        txtcantidad.setBackground(new java.awt.Color(153, 153, 153));
        txtcantidad.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txtcantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 30));

        txtprecio.setBackground(new java.awt.Color(153, 153, 153));
        txtprecio.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txtprecio.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 229, 100, 30));

        txtdescripcion.setBackground(new java.awt.Color(153, 153, 153));
        txtdescripcion.setColumns(20);
        txtdescripcion.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtdescripcion.setRows(5);
        jScrollPane2.setViewportView(txtdescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 350, 110));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Ingresar Producto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 160, 40));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Eliminar Producto ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 150, 40));

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 90, 70));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("2020. Jairo Gomez. Todos los derechos reservados.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 320, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Devolucion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 120, 30));

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion (1).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 90, 60));

        fechalabel.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        fechalabel.setForeground(new java.awt.Color(255, 255, 255));
        fechalabel.setText("0");
        getContentPane().add(fechalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, -1));

        labelfactura.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        labelfactura.setForeground(new java.awt.Color(255, 255, 255));
        labelfactura.setText("0");
        getContentPane().add(labelfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 70, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Descripcion");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 90, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Producto");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 70, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 540, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncajeroActionPerformed

        try {
            String cajero;
            do {
                cajero = JOptionPane.showInputDialog(null, "Ingrese el codigo del cajero");
                Principal.bd.AccesoCajero(cajero);
                if (Principal.accesoc != 1) {
                    JOptionPane.showMessageDialog(null, "Codigo de cajero erroneo.");
                }
            } while (Principal.accesoc != 1);

            botoncajero.setText("Cajero: " + cajero);
            Principal.accesoc = 0;
        } catch (Exception e) {
        }

    }//GEN-LAST:event_botoncajeroActionPerformed

    private void botonstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonstockActionPerformed
        Principal.lista.Limpiar();
        if (Principal.interfazdestock.isVisible()) {

            Principal.interfazdestock.toFront();
        } else {
            Stock.botonaceptar.setEnabled(true);
            Principal.bd.Stock();
            Principal.lista.ArregloStock();
            Principal.interfazdestock.setVisible(true);
        }
    }//GEN-LAST:event_botonstockActionPerformed

    private void botonclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonclienteActionPerformed

        Principal.mostrarcliente.setVisible(true);


    }//GEN-LAST:event_botonclienteActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cerrarfactura.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void botonvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvendedorActionPerformed
        try {
            String vendedor;
            do {
                vendedor= JOptionPane.showInputDialog(null, "Ingrese el codigo del vendedor");
                Principal.bd.AccesoVendedor(vendedor);
                if (Principal.accesov != 1) {
                    JOptionPane.showMessageDialog(null, "Codigo de vendedor erroneo.");
                }
            } while (Principal.accesov != 1);

            botonvendedor.setText("Vendedor: " + vendedor);
            Principal.accesov = 0;
        } catch (Exception e) {
        }

    }//GEN-LAST:event_botonvendedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // OBTENGO EL HEADER DE MI TABLA PARA CAMBIARLE EL COLOR.

        if (modelofacturacion.getRowCount() == 0) {
            Cambio();
            if (banderadevolucion == 0) {
                header.setBackground(Color.red);
                tablafacturacion.setBackground(Color.red);
                banderadevolucion = 1;
            } else if (banderadevolucion == 1) {
                header.setBackground(Color.white);
                tablafacturacion.setBackground(Color.white);
                banderadevolucion = 0;
            }
        } else {

            JOptionPane.showMessageDialog(null, "La tabla de facturacion debe estar vacía para activar o desactivar el modo devolución.");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            int aux = 0;

            if (banderacambio == 1) {
                Principal.bd.StockEmpresa();

            } else if (banderacambio == 0) {
                Principal.lista.Buscar();

            }

            if (Lista.bandera == 1 || BaseDatos.banderaempresa == 1) {

                String[] codigo = new String[modelofacturacion.getRowCount()]; // VECTOR DONDE ALMACENO TEMPORALMENTE EL CONTENIDO DE LA LISTA A FACTURAR.

                for (int i = 0; i < modelofacturacion.getRowCount(); i++) {

                    codigo[i] = String.valueOf(Facturacion.modelofacturacion.getValueAt(i, 0)); // LLENO EL VECTOR

                }

                for (int i = 0; i < modelofacturacion.getRowCount(); i++) {

                    if (txtcodigo.getText().equals(codigo[i])) {                            // VALIDO SI EL ITEM QUE SE VA A INGRESAR YA ESTA EN LA LISTA. 
                        aux = 1;

                    }

                }

                if (aux == 0) {

                    Principal.lista.ArregloFacturacion();
                    double cantidad = Double.parseDouble(txtcantidad.getText());
                    if (cantidad > 1) {                                           // ALGORITMO PARA MULTIPLICAR EL PRECIO SI ES MAS DE 1 UNIDAD POR CODIGO.
                        String temporal = txtprecio.getText();
                        String temporalcorto = temporal.substring(1, temporal.length());
                        double valor = Double.parseDouble(temporalcorto);
                        double multiplicado = valor * cantidad;

                        tablafacturacion.setValueAt(("€ " + (double) Math.round(multiplicado * 100d) / 100), modelofacturacion.getRowCount() - 1, 2); // SETEO EL VALOR MULTIPLICADO EN LA CELDA DE PRECIO DEL ARTICULO.

                    }

                    txtcodigo.setText("");
                    txtcantidad.setText("");
                    txtprecio.setText("");
                    txtdescripcion.setText("");

                    for (int i = 0; i < modelofacturacion.getRowCount(); i++) {
                        String cadenaprecio = String.valueOf(tablafacturacion.getValueAt(i, 2));
                        String cadenacorta = cadenaprecio.substring(1, cadenaprecio.length());   // ALGORITMO PARA SUMAR LOS PRECIOS DE LA TABLA AL TOTAL A ABONAR.
                        double preciofinal = Double.parseDouble(cadenacorta);
                        montototal += preciofinal;

                        String cadenaitem = String.valueOf(tablafacturacion.getValueAt(i, 3)); //ALGORITMO PARA SUMAR LOS ITEMS. 
                        int itementero = Integer.parseInt(cadenaitem);
                        itemstotal += itementero;
                    }

                    labelmonto.setText("€ " + (double) Math.round(montototal * 100d) / 100); // USO MATH.ROUND PARA REDUCIR EL NUMERO DE DECIMALES QUE QUIERO MOSTRAR. 
                    labelitems.setText(Integer.toString(itemstotal));
                    itemstotal = 0;
                    montototal = 0;
                } else {

                    JOptionPane.showMessageDialog(null, "El articulo que intenta ingresar ya está en la lista, si quiere agregar más cantidad eliminelo y edite la cantidad.");

                }
            }
            BaseDatos.banderaempresa = 0;
            Lista.bandera = 0; // RESETEO MI BANDERA PARA QUE NO HAYA PROBLEMAS. 

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Por favor seleccione un producto");
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int seleccion = tablafacturacion.getSelectedRow();
            String precioseleccionado = String.valueOf(tablafacturacion.getValueAt(seleccion, 2));
            String precioacortado = precioseleccionado.substring(1, precioseleccionado.length()); // OBTENGO DATO A BORRAR
            double preciofinal = Double.parseDouble(precioacortado);

            String itemseleccionado = String.valueOf(tablafacturacion.getValueAt(seleccion, 3));
            int itemfinal = Integer.parseInt(itemseleccionado);

            modelofacturacion.removeRow(seleccion);

            String montoactual = labelmonto.getText();
            String montoacortado = montoactual.substring(2, montoactual.length()); // OBTENGO MI TOTAL ACTUAL PARA RESTARLO CON EL DATO A BORRAR
            double montofinal = Double.parseDouble(montoacortado);

            String itemactual = labelitems.getText();
            int enteroitemactual = Integer.parseInt(itemactual);

            double total = montofinal - preciofinal;
            int itemtotal = enteroitemactual - itemfinal;

            // PINTO EN PANTALLA EL RESTANTE LUEGO DE BORRAR UN ITEM 
            labelitems.setText(Integer.toString(itemtotal));
            labelmonto.setText("€ " + (double) Math.round(total * 100d) / 100);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un articulo a eliminar.");

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    public void Cambio() {
        if (banderacambio == 0) {
            txtcodigo.setBackground(Color.red);
            txtprecio.setBackground(Color.red);
            txtcantidad.setBackground(Color.red);
            txtdescripcion.setBackground(Color.red);
            txtcantidad.setText("-1");
            txtcantidad.setEditable(false);
            if (!"".equals(txtprecio.getText())) {
                String temporal = txtprecio.getText();
                String temporalcorto = temporal.substring(1, temporal.length());
                double temporaldouble = Double.parseDouble(temporalcorto); // ALGORITMO PARA EL VALOR NEGATIVO. 
                double negativo = temporaldouble * 2;
                double negativofinal = temporaldouble - negativo;
                Facturacion.txtprecio.setText("€" + Double.toString(negativofinal));
            }
            banderacambio = 1;
        } else if (banderacambio == 1) {

            txtcodigo.setBackground(Color.white);
            txtprecio.setBackground(Color.white);
            txtcantidad.setBackground(Color.white);
            txtdescripcion.setBackground(Color.white);
            txtcantidad.setText("1");
            txtcantidad.setEditable(true);
            if (!"".equals(txtprecio.getText())) {
                String temporal = txtprecio.getText();
                String temporalcorto = temporal.substring(1, temporal.length());
                double temporaldouble = Double.parseDouble(temporalcorto); // ALGORITMO PARA EL VALOR NEGATIVO. 
                double negativo = temporaldouble * 2;
                double negativofinal = temporaldouble - negativo;
                Facturacion.txtprecio.setText("€" + Double.toString(negativofinal));
            }
            banderacambio = 0;
        }

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Cambio();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtcodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcodigoFocusLost
        if (!"".equals(txtcodigo.getText())) {    // VALIDO QUE EL CAMPO NO ESTE VACIO PARA QUE NO ME MUESTRE SIEMPRE EL MENSAJE DE "NO HAY STOCK".

            if (banderacambio == 0) {  // SI EL FOCUS SE PIERDE, VALIDA SI EL PRODUCTO TIPEADO ESTA EN SISTEMA. 
                Principal.bd.Stock();
                Principal.lista.Buscar();
                if (Lista.bandera == 0) {
                    aiuda = 1;
                    txtcantidad.setText("");
                    txtprecio.setText("");
                    txtdescripcion.setText("");
                }

                Lista.bandera = 0;
            } else if (banderacambio == 1) {
                Principal.bd.StockEmpresa();
                if (BaseDatos.banderaempresa == 0) {

                    JOptionPane.showMessageDialog(null, "El articulo " + txtcodigo.getText() + " no esta registrado en la base de datos.");
                    txtcodigo.setText("");
                    txtcantidad.setText("");
                    txtprecio.setText("");
                    txtdescripcion.setText("");
                }

            }

        }
        BaseDatos.banderaempresa = 0;
    }//GEN-LAST:event_txtcodigoFocusLost

    private void ValidarStock() { // VALIDO SI EL STOCK REQUERIDO ES MAYOR AL DISPONIBLE EN SISTEMA.

        boolean bandera;

        for (int i = 0; i < modelofacturacion.getRowCount(); i++) {

            bandera = Principal.lista.ChequeoStock(String.valueOf(Facturacion.modelofacturacion.getValueAt(i, 0)), String.valueOf(Facturacion.modelofacturacion.getValueAt(i, 3)));

            if (bandera) {
                auxstock = 1;
            }
        }

    }


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (modelofacturacion.getRowCount() == 0) {

            JOptionPane.showMessageDialog(null, "La lista está vacía, agregue algún producto para facturar.");
        } else {

            String cadena = labelmonto.getText();
            String cadenacorta = cadena.substring(1, cadena.length());
            double cadenadouble = Double.parseDouble(cadenacorta);

            auxiliarmonto = cadenadouble;
            double montopositivo = auxiliarmonto * -1;
            ValidarStock();

            if (botonvendedor.getText().equals("Vendedor") || botoncajero.getText().equals("Cajero")) {

                JOptionPane.showMessageDialog(null, "Debe seleccionar un cajero y/o vendedor.");

            } else {
                if (auxiliarmonto <= -1 && banderadevolucion == 1) {
                    JOptionPane.showMessageDialog(null, "Debe entregarle en efectivo al cliente: € " + montopositivo);
                    MediodePago.imprimiendofactura.Imprimir(cadena);
                } else if (auxiliarmonto <= -1) {
                    JOptionPane.showMessageDialog(null, "El importe total es negativo. Debe ajustar la factura antes de proceder al pago.");

                } else if (auxiliarmonto >= 1) {
                    if (auxstock != 1) {

                        MediodePago.labelimporte.setText("€" + (double) Math.round(auxiliarmonto * 100d) / 100);
                        MediodePago.labelrestante.setText("€" + (double) Math.round(auxiliarmonto * 100d) / 100);
                        mediodepago.setVisible(true);
                    }
                } else if (auxiliarmonto > -1 && modelofacturacion.getRowCount() != 0) {
                    if (auxstock != 1) {
                        interfazcambio.setVisible(true);
                    }
                }

            }
        }
        auxstock = 0; // REINICIO LA BANDERA.
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarfactura.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botoncajero;
    public static javax.swing.JButton botoncliente;
    private javax.swing.JButton botonstock;
    public static javax.swing.JButton botonvendedor;
    public static javax.swing.JLabel fechalabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel labelfactura;
    public static javax.swing.JLabel labelfecha;
    public static javax.swing.JLabel labelitems;
    public static javax.swing.JLabel labelmonto;
    private javax.swing.JTable tablafacturacion;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextArea txtdescripcion;
    public static javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
