/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Jairo
 */
public class PagoEfectivo extends javax.swing.JFrame {

    /**
     * Creates new form PagoEfectivo
     */
    public PagoEfectivo() {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelimporte = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtabono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IMPORTE A ABONAR:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 56, -1, -1));

        labelimporte.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        labelimporte.setForeground(new java.awt.Color(255, 255, 255));
        labelimporte.setText("abono");
        getContentPane().add(labelimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EFECTIVO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 124, -1, -1));

        txtabono.setBackground(new java.awt.Color(153, 153, 153));
        txtabono.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txtabono.setForeground(new java.awt.Color(0, 0, 0));
        txtabono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtabono, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 121, 140, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, 40));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        jLabel2.setText("IMPORTE A ABONAR:");
        jLabel2.setPreferredSize(new java.awt.Dimension(460, 287));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static double montoingresado;
public static int banderaefectivo = 0 ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String importe = labelimporte.getText();
            String importecorto = importe.substring(1, importe.length());

            double importedouble = Double.parseDouble(importecorto);

            String abono = txtabono.getText();
            double abonodouble = Double.parseDouble(abono);

            double total = importedouble - abonodouble;
            banderaefectivo=1;
            if (total > 0) { // VALIDO SI EL TOTAL DE LA FACTURA YA FUE ALCANZADO. ASI CIERRO O NO. 

                MediodePago.labelrestante.setText("€" + (double) Math.round(total * 100d) / 100);
                txtabono.setText("");
                this.setVisible(false);

            } else if (total <= 0) {

                double temporal = total * 2;
                double positivo = total - temporal;

                JOptionPane.showMessageDialog(null, "El vuelto para el cliente es: " + (double) Math.round(positivo * 100d) / 100);
                Facturacion.mediodepago.setVisible(false);
                
                this.setVisible(false);
                MediodePago.imprimiendofactura.setVisible(true);
                MediodePago.imprimiendofactura.Imprimir(MediodePago.labelimporte.getText()); // LLAMO AL METODO PARA QUE CORRA EL PROGRESO DE LA BARRA. 

            }
            txtabono.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el monto a abonar.");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtabono.setText("");
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtabonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabonoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        txtabono.setText("");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoEfectivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel labelimporte;
    public static javax.swing.JTextField txtabono;
    // End of variables declaration//GEN-END:variables
}
