package Interfaces;

import Logica.*;
import Base_datos.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jairo
 */
public class Principal extends javax.swing.JFrame {

    public void Cerrar() {

        String botones[] = {"Salir", "No salir"};

        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea salir de la aplicacion?", "Salir", 0, 0, null, botones, this);

        if (eleccion == JOptionPane.YES_OPTION) {

            System.exit(0);

        } else if (eleccion == JOptionPane.NO_OPTION) {

        }

    }

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);;

    }

    public static Bienvenida bienvenida = new Bienvenida();
    public static Stock interfazdestock = new Stock();
    public static BaseDatos bd = new BaseDatos();
    public static Lista lista = new Lista();
    public static Facturacion facturacion = new Facturacion();
    public static String codigocajero = "", codigovendedor = "";
    public static int accesoc = 0, accesov = 0; // BANDERAS PARA VALIDAR SI EL VENDEDOR INGRESADO ESTA EN LA BASE DE DATOS. 
    public static MostrarCliente mostrarcliente = new MostrarCliente();
    public static Cierres cierres = new Cierres();
    public static Date fecha = new Date();
    public static String fechadehoy = new SimpleDateFormat("dd-MM-yyyy").format(fecha);
    public static Transacciones transacciones = new Transacciones();
    public static ListaTransacciones listatransacciones = new ListaTransacciones();
    public static Egresos egresos = new Egresos();
    public static SeleccionClientes seleccionclientes = new SeleccionClientes();
    public static Comisiones comisiones = new Comisiones();
    public static ListaComisiones listacomisiones = new ListaComisiones();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b_facturacion = new javax.swing.JButton();
        b_transacciones = new javax.swing.JButton();
        b_cierre = new javax.swing.JButton();
        b_stock = new javax.swing.JButton();
        b_usuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        b_salir = new javax.swing.JButton();
        b_egresos = new javax.swing.JButton();
        b_clientes = new javax.swing.JButton();
        b_comisiones = new javax.swing.JButton();
        labelu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelusuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 674));
        setMinimumSize(new java.awt.Dimension(700, 674));
        setPreferredSize(new java.awt.Dimension(700, 723));
        setSize(new java.awt.Dimension(700, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_facturacion.setBackground(new java.awt.Color(153, 153, 153));
        b_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        b_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_facturacionActionPerformed(evt);
            }
        });
        getContentPane().add(b_facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 70));

        b_transacciones.setBackground(new java.awt.Color(153, 153, 153));
        b_transacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuenta.png"))); // NOI18N
        b_transacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_transaccionesActionPerformed(evt);
            }
        });
        getContentPane().add(b_transacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 90, 70));

        b_cierre.setBackground(new java.awt.Color(153, 153, 153));
        b_cierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaccion.png"))); // NOI18N
        b_cierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cierreActionPerformed(evt);
            }
        });
        getContentPane().add(b_cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 70));

        b_stock.setBackground(new java.awt.Color(153, 153, 153));
        b_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/valores.png"))); // NOI18N
        b_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_stockActionPerformed(evt);
            }
        });
        getContentPane().add(b_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 90, 70));

        b_usuario.setBackground(new java.awt.Color(153, 153, 153));
        b_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario (1).png"))); // NOI18N
        b_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(b_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transacciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 110, 24));

        b_salir.setBackground(new java.awt.Color(153, 153, 153));
        b_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion (1).png"))); // NOI18N
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        getContentPane().add(b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 60, 50));

        b_egresos.setBackground(new java.awt.Color(153, 153, 153));
        b_egresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/valores (1).png"))); // NOI18N
        b_egresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_egresosActionPerformed(evt);
            }
        });
        getContentPane().add(b_egresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 90, 70));

        b_clientes.setBackground(new java.awt.Color(153, 153, 153));
        b_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        b_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(b_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 90, 70));

        b_comisiones.setBackground(new java.awt.Color(153, 153, 153));
        b_comisiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero.png"))); // NOI18N
        b_comisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_comisionesActionPerformed(evt);
            }
        });
        getContentPane().add(b_comisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 90, 70));

        labelu.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labelu.setForeground(new java.awt.Color(255, 255, 255));
        labelu.setText("Hola!");
        getContentPane().add(labelu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CAJA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MERCADERIA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONSULTAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 140, -1));

        labelusuario.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        labelusuario.setForeground(new java.awt.Color(255, 255, 255));
        labelusuario.setText("Administrador");
        getContentPane().add(labelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 120, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 40, 24));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("VENTAS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 24));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cierre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 24));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Egresos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 60, 24));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Clientes");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, 24));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Comisiones");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 90, 24));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Stock");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, 24));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 700, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 700, 30));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 20));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Facturacion");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 24));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 700, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        Cerrar();
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_usuarioActionPerformed
        this.setVisible(false);
        b_egresos.setEnabled(true);
        bienvenida.setVisible(true);
    }//GEN-LAST:event_b_usuarioActionPerformed

    private void b_egresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_egresosActionPerformed
        bd.Remito();
        int id = BaseDatos.idremito;

        if (id < 10) {
            Egresos.numeroremito.setText("0000" + Integer.toString(id));
        } else if (id < 100) {
            Egresos.numeroremito.setText("000" + Integer.toString(id)); // VALIDO EL TAMANO DEL NRO DE FACTURA PARA PINTARLO BIEN EN LA INTERFAZ. 
        } else if (id < 1000) {
            Egresos.numeroremito.setText("00" + Integer.toString(id));
        } else if (id < 10000) {
            Egresos.numeroremito.setText("0" + Integer.toString(id));
        } else if (id < 100000) {
            Egresos.numeroremito.setText(Integer.toString(id));
        }

        egresos.setVisible(true);
    }//GEN-LAST:event_b_egresosActionPerformed

    private void b_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_stockActionPerformed
        Principal.lista.Limpiar();
        Stock.botonaceptar.setEnabled(false);
        bd.Stock();
        lista.ArregloStock();
        interfazdestock.setVisible(true);


    }//GEN-LAST:event_b_stockActionPerformed

    private void b_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_facturacionActionPerformed
        try {
            if (bd.CierreDeHoy(fechadehoy)) {

                JOptionPane.showMessageDialog(null, "Se realizó el cierre del día de hoy correctamente. La facturación está deshabilitada hasta el día de mañana.");
            } else {

                if (ChequeandoCierres() || condicioncierre.equals(fechadehoy)) {// VALIDO SI HACE FALTA CERRAR LA CAJA DEL DIA ANTERIOR.

                    codigocajero = JOptionPane.showInputDialog(null, "Introduzca el código del cajero");

                    if (codigocajero != null) { // VALIDO SI EL USUARIO LE DIO CANCELAR.
                        bd.AccesoCajero(codigocajero);
                    }
                    
                    if (accesoc == 1) {
                        codigovendedor = JOptionPane.showInputDialog(null, "Introduzca el código del vendedor");

                        if (codigovendedor != null) { // VALIDO SI EL USUARIO LE DIO CANCELAR.
                            bd.AccesoVendedor(codigovendedor);
                        }

                        if (accesov == 1) {

                            facturacion.setVisible(true);   // VALIDO QUE LOS DATOS INGRESADOS ESTEN EN LA DB

                        } else {
                            JOptionPane.showMessageDialog(null, "Codigo de vendedor incorrecto.");

                        }
                    } else {

                        JOptionPane.showMessageDialog(null, "Codigo de cajero incorrecto.");
                    }

                    if (accesov == 1 && accesoc == 1) { // VALIDO SI EL ACCESO DE LOS CAJEROS ES CORRECTO. 

                        Facturacion.botonvendedor.setText("VENDEDOR: " + codigovendedor);
                        Facturacion.botoncajero.setText("CAJERO: " + codigocajero);

                        Facturacion.fechalabel.setText(fechadehoy);

                        bd.Factura();
                        Facturacion.numfactura = BaseDatos.idfactura; // BUSCO EL NUMERO DE FACTURA.

                        if (Facturacion.numfactura < 10) {
                            Facturacion.labelfactura.setText("0000" + Integer.toString(Facturacion.numfactura));
                        } else if (Facturacion.numfactura < 100) {
                            Facturacion.labelfactura.setText("000" + Integer.toString(Facturacion.numfactura)); // VALIDO EL TAMANO DEL NRO DE FACTURA PARA PINTARLO BIEN EN LA INTERFAZ. 
                        } else if (Facturacion.numfactura < 1000) {
                            Facturacion.labelfactura.setText("00" + Integer.toString(Facturacion.numfactura));
                        } else if (Facturacion.numfactura < 10000) {
                            Facturacion.labelfactura.setText("0" + Integer.toString(Facturacion.numfactura));
                        } else if (Facturacion.numfactura < 100000) {
                            Facturacion.labelfactura.setText(Integer.toString(Facturacion.numfactura));
                        }

                        facturacion.setVisible(true);
                        this.setVisible(false);

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Debe realizar un cierre de caja antes de continuar facturando.");
                    Cierres.labelfecha.setText(condicioncierre);
                    bd.TotalCierre(Cierres.labelfecha.getText());
                    cierres.setVisible(true);
                }

                BaseDatos.temp = 0;
            }

            accesov = 0;
            accesoc = 0;
        } catch (Exception e) {
        }

    }//GEN-LAST:event_b_facturacionActionPerformed

    public String condicioncierre;

    public boolean ChequeandoCierres() {
        bd.ValidoTransacciones();
        condicioncierre = bd.VerificoCierres();
        return condicioncierre.equals("no"); // SI SE CUMPLE LA CONDICION DE QUE CONDICIONCIERRE SEA IGUAL A "NO" SE DEVUELVE TRUE, CASO CONTRARIO FALSE.
    }


    private void b_cierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cierreActionPerformed

        if (ChequeandoCierres()) {
            JOptionPane.showMessageDialog(null, "No hay cierres por realizar.");
        } else {

            Cierres.labelfecha.setText(condicioncierre);
            bd.TotalCierre(Cierres.labelfecha.getText());

            cierres.setVisible(true);

        }
        BaseDatos.temp = 0;
    }//GEN-LAST:event_b_cierreActionPerformed

    private void b_transaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_transaccionesActionPerformed
        listatransacciones.Limpiar();
        bd.GuardoTransacciones();
        listatransacciones.ArregloTransacciones();
        transacciones.setVisible(true);
    }//GEN-LAST:event_b_transaccionesActionPerformed

    private void b_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clientesActionPerformed
        seleccionclientes.setVisible(true);
    }//GEN-LAST:event_b_clientesActionPerformed

    private void b_comisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_comisionesActionPerformed
        listacomisiones.Limpiar();
        Comisiones.modelocomisiones.setRowCount(0);
        bd.GuardarComisiones();
        listacomisiones.ArregloComisiones();
        listacomisiones.TotalesLocal();
        comisiones.setVisible(true);
    }//GEN-LAST:event_b_comisionesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                bienvenida.setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cierre;
    private javax.swing.JButton b_clientes;
    private javax.swing.JButton b_comisiones;
    public javax.swing.JButton b_egresos;
    private javax.swing.JButton b_facturacion;
    public javax.swing.JButton b_salir;
    private javax.swing.JButton b_stock;
    private javax.swing.JButton b_transacciones;
    private javax.swing.JButton b_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public static javax.swing.JLabel labelu;
    public javax.swing.JLabel labelusuario;
    // End of variables declaration//GEN-END:variables
}
