/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.Lista;
import Base_datos.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jairo
 */
public class Stock extends javax.swing.JFrame {

    public static DefaultTableModel modelo = new DefaultTableModel() { // HAGO QUE LAS CELDAS NO SEAN EDITABLES 
        @Override
        public boolean isCellEditable(int row, int column) {
            if (column == 4) {
                return true;

            } else {
                return false;

            }

        }

    };

    TableRowSorter trs; // PARA FILTRAR EN LA BUSQUEDA 

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        modelo.addColumn("CODIGO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO");
        modelo.addColumn("STOCK");
        tabla.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonaceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtfiltro = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(652, 569));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonaceptar.setBackground(new java.awt.Color(153, 153, 153));
        botonaceptar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        botonaceptar.setForeground(new java.awt.Color(0, 0, 0));
        botonaceptar.setText("Aceptar");
        botonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 497, 100, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 90, -1));

        txtfiltro.setBackground(new java.awt.Color(153, 153, 153));
        txtfiltro.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txtfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfiltroActionPerformed(evt);
            }
        });
        txtfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfiltroKeyTyped(evt);
            }
        });
        getContentPane().add(txtfiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 274, 30));

        tabla.setBackground(new java.awt.Color(222, 222, 222));
        tabla.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabla);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 590, 360));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        jLabel1.setText("BUSCAR :");
        jLabel1.setPreferredSize(new java.awt.Dimension(652, 569));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiltroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        modelo.setRowCount(0);

    }//GEN-LAST:event_jButton2ActionPerformed


    private void txtfiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfiltroKeyTyped

        // PARA FILTRAR LA BUSQUEDA
        txtfiltro.addKeyListener(new KeyAdapter() { // PARA FILTRAR LA BUSQUEDA INGRESANDO POR TECLADO. 
            @Override
            public void keyReleased(KeyEvent e) {

                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtfiltro.getText(), 0)); // EL ?i LO QUE HACE ES NO DISTINGUIR ENTRE MAYUSCULAS Y MINUSCULAS. 

            }

        });

        trs = new TableRowSorter(modelo);
        tabla.setRowSorter(trs);


    }//GEN-LAST:event_txtfiltroKeyTyped

    private void botonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaceptarActionPerformed

        try {
            int seleccion = tabla.getSelectedRow();
            String cod = String.valueOf(modelo.getValueAt(seleccion, 0));
            String desc = String.valueOf(modelo.getValueAt(seleccion, 1));
            String pre = String.valueOf(modelo.getValueAt(seleccion, 2));
            double montototal = 0.0;
            int itemstotal = 0;

            if (Egresos.banderaegresos) {

                Principal.lista.ListaEgresos(cod, desc, pre);

                for (int i = 0; i < Egresos.modeloegresos.getRowCount(); i++) {
                    String cadenaprecio = String.valueOf(Egresos.tablaegresos.getValueAt(i, 2));
                    String cadenacorta = cadenaprecio.substring(1, cadenaprecio.length());   // ALGORITMO PARA SUMAR LOS PRECIOS DE LA TABLA AL TOTAL A ABONAR.
                    double preciofinal = Double.parseDouble(cadenacorta);
                    montototal += preciofinal;

                    String cadenaitem = String.valueOf(Egresos.tablaegresos.getValueAt(i, 3)); //ALGORITMO PARA SUMAR LOS ITEMS. 
                    int itementero = Integer.parseInt(cadenaitem);
                    itemstotal += itementero;
                }
                Egresos.labeltotal.setText("€ " + (double) Math.round(montototal * 100d) / 100);
                Egresos.labelarticulos.setText(Integer.toString(itemstotal));
                this.setVisible(false);
                modelo.setRowCount(0);
                Egresos.banderaegresos = false;
            } else {
                Principal.lista.MostrarLista();
                this.setVisible(false);
                modelo.setRowCount(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un articulo");
        }
    }//GEN-LAST:event_botonaceptarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        modelo.setRowCount(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Stock().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botonaceptar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable tabla;
    private javax.swing.JTextField txtfiltro;
    // End of variables declaration//GEN-END:variables
}
