/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.ListaTransacciones;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jairo
 */
public class Transacciones extends javax.swing.JFrame {

    public static DefaultTableModel modelotransacciones = new DefaultTableModel() { // HAGO QUE LAS CELDAS NO SEAN EDITABLES 
        @Override
        public boolean isCellEditable(int row, int column) {
            if (column == 7) {
                return true;

            } else {
                return false;

            }

        }

    };

    /**
     * Creates new form Transacciones
     */
    public Transacciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        tablatransacciones.setModel(modelotransacciones);
        modelotransacciones.addColumn("Fecha");
        modelotransacciones.addColumn("Factura");
        modelotransacciones.addColumn("Monto");
        modelotransacciones.addColumn("Articulos");
        modelotransacciones.addColumn("Unidades");
        modelotransacciones.addColumn("Cajero");
        modelotransacciones.addColumn("Vendedor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        calendar1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calendar2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablatransacciones = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar1.setBackground(new java.awt.Color(153, 153, 153));
        calendar1.setForeground(new java.awt.Color(0, 0, 0));
        calendar1.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(calendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 611, 142, 31));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 667, 95, 43));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtrar desde: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtrar hasta: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        calendar2.setBackground(new java.awt.Color(153, 153, 153));
        calendar2.setForeground(new java.awt.Color(0, 0, 0));
        calendar2.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(calendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 660, 142, 31));

        tablatransacciones.setBackground(new java.awt.Color(204, 204, 204));
        tablatransacciones.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        tablatransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablatransacciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, 837, 562));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 630, 117, 34));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/94017.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(861, 729));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        modelotransacciones.setRowCount(0);
        Principal.listatransacciones.Limpiar();
        calendar1.setDate(Principal.fecha);
        calendar2.setDate(Principal.fecha);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ListaTransacciones.bandera = false;
            Date date = calendar1.getDate();
            String obtenerfecha = new SimpleDateFormat("dd-MM-yyyy").format(date);
            Date date2 = calendar2.getDate();
            String obtenerfecha2 = new SimpleDateFormat("dd-MM-yyyy").format(date2);

            String dia_ini = obtenerfecha.substring(0, 2);
            String mes_ini = obtenerfecha.substring(3, 5);
            String year_ini = obtenerfecha.substring(6, 10);

            String dia_fin = obtenerfecha2.substring(0, 2);
            String mes_fin = obtenerfecha2.substring(3, 5);
            String year_fin = obtenerfecha2.substring(6, 10);

            int idia = Principal.listatransacciones.ParsearCadena(dia_ini);
            int imes = Principal.listatransacciones.ParsearCadena(mes_ini);
            int iyear = Principal.listatransacciones.ParsearCadena(year_ini);

            int fdia = Principal.listatransacciones.ParsearCadena(dia_fin);
            int fmes = Principal.listatransacciones.ParsearCadena(mes_fin);
            int fyear = Principal.listatransacciones.ParsearCadena(year_fin);

            if (iyear > fyear) {                                                                                                                                           //VALIDACIONES PARA QUE EL USUARIO NO INTRODUZCA MAL LAS FECHAS.
                JOptionPane.showMessageDialog(null, "La fecha final no puede ser menor que la inicial.");

            } else if (iyear == fyear) {

                if (imes > fmes) {
                    JOptionPane.showMessageDialog(null, "La fecha final no puede ser menor que la inicial.");
                } else if (imes == fmes) {

                    if (idia > fdia) {
                        JOptionPane.showMessageDialog(null, "La fecha final no puede ser menor que la inicial.");

                    } else {
                        Principal.listatransacciones.AsignoValores(obtenerfecha, obtenerfecha2);

                    }

                } else {
                    Principal.listatransacciones.AsignoValores(obtenerfecha, obtenerfecha2);

                }

            } else {

                Principal.listatransacciones.AsignoValores(obtenerfecha, obtenerfecha2);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Por favor ingrese las fechas correctamente.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        modelotransacciones.setRowCount(0);
        Principal.listatransacciones.Limpiar();
        calendar1.setDate(Principal.fecha);
        calendar2.setDate(Principal.fecha);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transacciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendar1;
    private com.toedter.calendar.JDateChooser calendar2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablatransacciones;
    // End of variables declaration//GEN-END:variables
}
